version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql:/var/lib/mysql

  app:
    image: kholiq/todo:latest
    container_name: app
    restart: always
    ports:
      - 8080:3030
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DBNAME: test

volumes:
  mysql:
