// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package querier

import (
	"context"
)

type Querier interface {
	DeleteActivityGroup(ctx context.Context, id int32) error
	GetActivityGroup(ctx context.Context, id int32) (ActivityGroup, error)
	ListActivityGroups(ctx context.Context) ([]ActivityGroup, error)
}

var _ Querier = (*Queries)(nil)
